### ISSUE TITLE
Detecting network activity from injected scripts

### ISSUE THREAD

**Issue by mattrheault** [w3c-webmob/ServiceWorkersDemos#22]
Hiya, i built out https://www.whataremybrowserextensionsdoing.com as an example of something that would be very difficult if not impossible to do without a service worker. Do you think this example belongs in this repo? If so I'd be happy to put together a PR. If not then forgive me for the intrusion :smile:

**Comment by marcoscaceres** [comment]
@mattrheault, sorry for taking so long to respond! Unfortunately, we are not really maintaining this repo anymore (I'll update the README): since we started this work, great resources have become available for developers.
